### ISSUE TITLE
Not saving profiles

### ISSUE THREAD

**Issue by Madpaddy** [matortheeternal/merge-plugins#1]
The latest 593 wont load a previous profile on start, even after making a new profile on restart it shows an empty select profile screen.

**Comment by matortheeternal** [comment]
This was resolved two days ago with the latest build.  You're using Windows 8 or newer, right?
Make sure you have build 593.

**Comment by Madpaddy** [comment]
Im using windows 10, but its build 593 thats causing this problem for me mate.

**Comment by Madpaddy** [comment]
Ps that rebalancer mod you made for me wont work with the latest MTEfunctions any chance you could recompile it for me please.

**Comment by matortheeternal** [comment]
@Madpaddy Yeah, I found the issue.  It's just not saving some stuff in the settings correctly, so it's ignoring the profile because it is invalid.  I'll fix it quickly (before the end of today).

Yes on Rebalancer, can you PM me your current version on the Nexus so I make sure I adjust the version you're using?  I've kind of lost track of things with that project so that would help

**Comment by Madpaddy** [comment]
Yeah will do mate cheers.

**Comment by matortheeternal** [comment]
Resolved in build 594.

**Comment by Madpaddy** [comment]
Great work mate thank you.
