### ISSUE TITLE
fallout3.esm filename lowercase?

### ISSUE THREAD

**Issue by InsanePlumber** [matortheeternal/merge-plugins#113]
This only applies to Fallout 3. (MP 2.1.3)
I was unable to repeat that for OBL FNV or SKY.

Firstly, you can add Fallout3.esm to Merge and is displayed in lowercase. (fallout3.esm)
http://i.imgur.com/q0yUKdi.jpg

Secondly, when checking errors master plugin (Fallout3.em) It is also checked
As MP does not merge master plugin (Fallout3.em) or DLC's I see no need to check errors in them. (unless I do not understand something)
http://i.imgur.com/DFTztYN.jpg

Archive with log and Fallout 3 profile.
https://drive.google.com/file/d/0B6ioBcQsnDXDcEY5Y3o3M2ZFLWc/view?usp=sharing

The situation is repeated when we remove ...\Merge Plugins\Profiles\Fallout 3\PluginInfo.json

EDIT
I started translating for Polish language.
When I finish I'll give you link to the translated file.
Unfortunately, I do not know when exactly it will be done.

**Comment by matortheeternal** [comment]
It appears the issue is fallout3.esm isn't blacklisted.  This isn't an issue with the program, but rather with the dictionary definitions for Fallout 3.  Looking at the dictionary file, it appears the filename is usually capitalized.  You should verify you haven't changed that in your setup.

`Fallout3.esm;808699;2.0;-1.0;2;[User: Hishutp] [Hash: C092218B] [Version: 2.0]@13Official Plugin, do not merge.@13@13[User: hishutup] [Hash: C092218B] [Version: 2.0]@13Main ESM, do not merge@13@13`

**Comment by InsanePlumber** [comment]
For some unknown reason for me in C:\Users\USERNAME\AppData\Local\Fallout3\plugins.txt
Fallout3.esm It was written with a lower case letter (fallout3.esm)
When I correct this everything works as it should.
Thank you.

**Comment by matortheeternal** [comment]
Awesome, glad to hear you got it fixed!
