### ISSUE TITLE
Merge Plugins ordering plugins wrong for FO3/FNV/TES4

### ISSUE THREAD

**Issue by InsanePlumber** [matortheeternal/merge-plugins#60]
Merge Plugins can not read properly of Load Order for FO3\NV.

Wrye Flash Load Order (FO3)
http://imgur.com/AZnoUHm

Merge Plugins Load Order (FO3)
http://imgur.com/6kLnNAV

Wrye Flash Load Order (FNV)
http://imgur.com/zJSNf7i

Merge Plugins Load Order (FNV)
http://imgur.com/lHWa9hD

For Skyrim is working properly.

EDIT
Want to add that I have never had problems with earlier versions of Merge Plugins.(apart from those reported previous)
I "installed" Merge Plugins (2.1.1) from scratch.
Removed the old profiles allow for the creation of new ones.
Everything has been detected correctly.
- I have installed the Games on a different disk than Windows so no problem with UAC.
- I run Merge Plugins with administrator privileges.

**Comment by hishutup** [comment]
When loading LO without any plugins selected, the LO is correct.
When loading all ESMs in order the LO is correct, however when one ESP is selected the order gets all messed up.

**Comment by Roofcrawler** [comment]
I use MO as well, and I'm getting this problem for FO3.
In the logfile, it says it's getting the load order from 
12:50:49 (GENERAL) Load Order: Using C:\Users\'_____\AppData\Local\Fallout3\

That's not where the loadorder.txt I want to use is. The one I want to use is in 
D:\Games\Steam\steamapps\common\Fallout 3 goty\Mod Organizer\profiles\Clear and Present Danger

Just figured you might want to know where the program is looking for loadorder.txt.

**Comment by matortheeternal** [comment]
Yes, I'm seeing this problem with Oblivion as well (not getting the loadorder.txt for the Mod Organizer profile I'm using)

**Comment by matortheeternal** [comment]
I seem to have found the issue when using Mod Organizer.  I'll upload a dev build.

**Comment by matortheeternal** [comment]
Here is a devbuild:
http://puu.sh/m9xyu.zip

If one or more of you could test to make sure this gets the load order right, that would be awesome.  It works for me for Oblivion.

**Comment by Roofcrawler** [comment]
Just tested the devbuild through Mod Organizer, load order detection works.

**Comment by matortheeternal** [comment]
Thanks @Roofcrawler

**Comment by matortheeternal** [comment]
Still having problems with FNV load order, according to some users.

**Left4Gamer1:**

Hello, I'm having problems with the load order when trying to load the FalloutNV profile. It's nothing like my actual load order, and the master plugin (Fallout.esm) isn't the first to load, loading actually after some DLCs which seems to be causing an issue where my plugins won't load properly. This issue is only occurring in FalloutNV, as with Skyrim the load order is correct. 

**ImANomad:**

Version 2.1.2
Fnv profile still can't get load order work right and because of that i can't use your program at all.
http://imgur.com/sfXECKH
Also if i minimize program window with "show desktop" button at windows task bar i stuck with it unable to get it back and have to terminate process through the task manager.

**Comment by matortheeternal** [comment]
According to user reports NMM load orders for FNV and TES4 and (presumably) FO3 are the ones that are still incorrect.  MO load orders are correct for all games.

**Comment by InsanePlumber** [comment]
@matortheeternal 
For me it still works properly only for Skyrim. (Hotfix v2.1.2)
I do not use MO or NMM.

**Comment by matortheeternal** [comment]
@InsanePlumber using NMM is equivalent to using no Mod Manager as far as the current code is concerned.

**Comment by matortheeternal** [comment]
I think I fixed it.  Can someone please test this dev build: [Dev build 2.1.2.1](http://puu.sh/meI0I.zip)

**Comment by InsanePlumber** [comment]
I confirm the correct reading of Load Order for SKY,FO3,FNV.
When MP starts to merge modifications for FO4 You Really Will Be ETERNAL.
Thank you Mator !

In the evening (about eight hours after writing this) I check how new version works on the front of merging modifications for FO3/FNV.

Just out of curiosity (if it is not a problem), what was the problem?

**Comment by matortheeternal** [comment]
@InsanePlumber awesome!  Finally.

The problem was I didn't get the file age information for the loadorder.txt list.  I did it for plugins.txt, but not loadorder.txt, so when the program went to sort that list it just messed up.  It was literally one line of code:`GetPluginDates(slLoadOrder);`.  1f6a517
